'use strict';
const width = 100;
const height = 300;
const area = width * height;
console.log('The area of this space is:', area);
console.log('The typeof', typeof area);
const bill = 50;
const payment = 100;
const change = payment - bill;
console.log('The result of change', change);
console.log('The typeof', typeof change);
const quizzes = 90;
const midterm = 80;
const final = 50;
const grade = quizzes + midterm + final / 3;
console.log('The average grade is', grade);
console.log('The typeof average', typeof grade);
const firstName = 'Howard';
const lastName = 'Hut';
const fullName = firstName + ' ' + lastName;
console.log('The name is', fullName);
console.log('The typeof name', typeof fullName);
const pH = 6;
const isAcidic = pH < 7;
console.log('Is the ph acidic', isAcidic);
console.log('What is the type', isAcidic);
const headCount = 220;
const isSparta = headCount === 300;
console.log('What is it Sparta', isSparta);
console.log('The typeof', typeof isSparta);
let motto = fullName;
motto += ' is the Goat';
console.log('Results:', motto);
console.log('It is a typeof', typeof motto);
